Repository pysal/spopt, pull requests merged in 2020-04, with the labels that each got.

#22 streamlining GHA testing
  .github/workflows/unittests.yml
Labels: testing

#23 Tests and docs (draft) for maxp
  notebooks/maxp.ipynb
  spopt/region/maxp.py
  spopt/tests/test_maxp.py
  spopt/tests/test_region_k_means.py
Labels: docs, testing

#25 Add testing for Python 3.8
  .github/workflows/unittests.yml
  ci/38.yaml
  setup.py
Labels: maintenance, testing

#26 DOC: README
  README.md
Labels: docs

#27 setting up codecov GitHub Action
  .github/workflows/unittests.yml
Labels: code coverage, testing

#29 test, codecov, and license badges in README
  README.md
Labels: docs

#30 DOC: maxp notebook
  README.md
  notebooks/maxp.ipynb
  spopt/BaseClass.py
  spopt/region/base.py
Labels: notebooks

#31 removing empty example template
  notebooks/example.ipynb
Labels: notebooks
