Repository pysal/spopt, pull requests merged in 2020-08, with the labels that each got.

#55 Updating README.md & adding CONTRIBUTING.md
  .github/CONTRIBUTING.md
  README.md
Labels: docs

#58 Setup correction
  setup.py
Labels: maintenance, rough edge

#59 adding .github/dependabot.yml
  .github/dependabot.yml
Labels: maintenance

#64 change < to ==
  spopt/region/maxp.py
Labels: bug, region

#62 removing python-mip language from REAMDE
  README.md
Labels: docs
