Repository pysal/spopt, pull requests merged in 2021-01, with the labels that each got.

#90 Add back images that were deleted
  docs/_static/images/pysal_banner.svg
  docs/_static/images/pysal_favicon.ico
  docsrc/_static/images/pysal_banner.svg
  docsrc/_static/images/pysal_favicon.ico
Labels: maintenance

#104 add docs badge to README.md
  README.md
Labels: docs

#108 Update installation.rst
  docs/installation.rst
Labels: docs

#111 Polish up and minor docs/reqs fixes
  .ci/37.yaml
  .ci/38.yaml
  .ci/39.yaml
  .coveragerc
  LICENSE.txt
  MANIFEST.in
  codecov.yml
  docs/conf.py
  docs/installation.rst
  environment.yml
  requirements.txt
  requirements_dev.txt
  requirements_docs.txt
  requirements_tests.txt
  setup.py
Labels: maintenance, priority: high

#114 Update notebook env
  README.md
  environment.yml
  notebooks/azp.ipynb
  notebooks/maxp.ipynb
  notebooks/reg-k-means.ipynb
  notebooks/skater.ipynb
  notebooks/ward.ipynb
Labels: notebooks/binders

#117 bump initial version down to 0.0.1
  .github/workflows/build_docs.yml
  setup.py
  spopt/__init__.py
Labels: priority: high, ready for review

#120 bump version to v0.0.2
  spopt/__init__.py
Labels: GitHub Actions, release

#122 update changelog notebook
  spopt/__init__.py
  tools/gitcount.ipynb
Labels: release

#123 Add Zenodo DOI and citation
  README.md
  docs/index.rst
  spopt/__init__.py
Labels: release

#124 update docs & README
  README.md
  docs/_static/pysal-styles.css
  docs/_static/references.bib
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/tutorials.rst
Labels: docs

#127 Revert pysal-styles.ccs, etc.
  docs/_static/pysal-styles.css
  environment.yml
Labels: docs

#129 add __token__ user to pypi step
  .github/workflows/release_and_publish.yml
  README.md
  spopt/locate/__init__.py
  spopt/transport/__init__.py
Labels: GitHub Actions, conda-forge, priority: high, pypi

#133 pulp to reqs
  requirements.txt
  spopt/__init__.py
Labels: requirements

#136 bump v0.1.0
  notebooks/azp.ipynb
  notebooks/maxp.ipynb
  notebooks/reg-k-means.ipynb
  notebooks/skater.ipynb
  notebooks/ward.ipynb
  spopt/__init__.py
Labels: release

#139 bump version 0.1.0 -> 0.1.1
  spopt/__init__.py
Labels: release
