Repository pysal/spopt, pull requests merged in 2025-05, with the labels that each got.

#484 Update numpy array comparisons to use isin
  spopt/region/csgraph_utils.py
Labels: maintenance

#482 ENH: add Spatial Adaptive Agglomerative Aggregation (SA3) regionalisation algorithm
  .github/workflows/testing.yml
  ci/311-latest.yaml
  ci/312-latest.yaml
  ci/313-dev.yaml
  ci/313-latest.yaml
  docs/conf.py
  notebooks/morphotopes.png
  notebooks/sa3.ipynb
  spopt/region/__init__.py
  spopt/region/sa3.py
  spopt/tests/test_sa3.py
Labels: enhancement, region

#486 bump libpysal requirement to 4.10
  ci/311-oldest.yaml
  environment.yml
  pyproject.toml
  spopt/region/sa3.py
  spopt/tests/test_sa3.py
Labels: dependencies
